const data ={
	status: "success",
	items: [
		{
			id: 1,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 2,
			title: "Nike Dunk Low Off-White Pine Green",
			price: 304,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 3,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 4,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 5,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 6,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 7,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 8,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 9,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{
			id: 10,
			title: "Nike LD Waffle Sacai Black Nylon",
			price: 401,
......		image:  "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
	 		category: "nike",
			img1:   "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
			img2: ".jpg?auto=format,compress&q=90&updated-at=1606321430&w=1000",
			cantidad: 1,
		},
		{

			